server:
  context-path: /mail-producer
  port: 8001
  session:
    timeout: 900
    
    
    
## Spring配置:
spring: 
  http: 
    encoding:
      charset: UTF-8 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL      
  redis:
    pool:
      min-idle: 100
      max-idle: 100
      max-wait: -1
      max-active: 1000
    timeout: 6000
    cluster:
      max-redirects: 1000
      nodes:
        - 192.168.1.20:7001
        - 192.168.1.20:7002
        - 192.168.1.20:7003
        - 192.168.1.20:7004
        - 192.168.1.20:7005
        - 192.168.1.20:7006

  mail:
    default-encoding: UTF-8
    host: smtp.163.com   
    port: 25
    username: test@163.com
    password: test
    properties: 
      mail:
        smtp: 
          auth: true
          timeout: 30000
                
druid: 
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql://192.168.1.20:3306/mail-1.0?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initialSize: 5
        minIdle: 1
        #maxIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        useGlobalDataSourceStat: true
    slave: 
        url: jdbc:mysql://192.168.1.21:3306/mail-1.0?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initialSize: 5
        minIdle: 1
        #maxIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        useGlobalDataSourceStat: true
        
mybatis:
    type-aliases-package: com.mawenxia.mail
    mapper-locations: classpath:com/mawenxia/mail/mapping/*.xml

logging:
    level:
        tk.mybatis: TRACE  
        
        
pagehelper: 
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql      
      
      
     
    